In [1]:
#  IMPORTING THE BASIC LIBRARY 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# To load the dataset
df = pd.read_csv("iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
# checnk the species column for catagory
df["species"].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [4]:
# Check the null values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
# Select Input and Output from data
X = df.drop("species",axis = 1)   # Input
Y = df["species"]   # Output

In [7]:
# But our output is in object type
# So LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [8]:
# Create the object of LabelEncoder
lr = LabelEncoder()
Y = lr.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=1)

In [10]:
X_train.shape

(105, 4)

In [11]:
# Scaling : StandardScaler() on INPUT
from sklearn.preprocessing import StandardScaler

In [12]:
# Create the object of StandardScaler class
ss = StandardScaler()
X_train = ss.fit_transform(X_train)  # Training
X_test = ss.fit_transform(X_test)    # Testing

In [13]:
# Peform Gaussian Naive BAYES theorem
# Training the Dataset
from sklearn.naive_bayes import GaussianNB
# inbuilt class GaussianNB

In [14]:
# GaussianNB ALOGRITHMS are applied on contienous Numerical Value of Input column
# Create the object GaussianNB 
gnb = GaussianNB()

In [15]:
# train the model
gnb.fit(X_train,Y_train)

GaussianNB()

In [16]:
# Test the model with data
Y_pred = gnb.predict(X_test)

In [17]:
# Classification report 
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [18]:
print("Classificaiton Report")
print(classification_report(Y_test,Y_pred))
print("Confusion Matrix")
print(confusion_matrix(Y_test,Y_pred))

Classificaiton Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

Confusion Matrix
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
