# 1. MinMaxScaler : 
      Formula of MinMaxScaler  = (X-min(X)) / (Max(X) - min(X))

In [1]:
# This necessary library used in data science 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings   # to avoid the warnings during executing the program
warnings.filterwarnings('ignore')

In [2]:
#Suppose create 1D numpy array a and b
a= np.array([10,20,30,40,50])
b= np.array([100,200,300,400,500])
print('a : ')
print(a)
print('b : ')
print(b)

a : 
[10 20 30 40 50]
b : 
[100 200 300 400 500]


### Create User Defined function for MinMaxScaler 

In [3]:
def minmax(X):
    new_output = (X-X.min())/(X.max() - X.min())
    return new_output


In [4]:
# Call in main Program
a = minmax(a)   # Call function
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
# Call in main Program
b = minmax(b)   # Call function
print(b)

[0.   0.25 0.5  0.75 1.  ]


# 2.) StandardScaler 

In [6]:
#Suppose create 1D numpy array a and b
a= np.array([10,20,30,40,50])
b= np.array([100,200,300,400,500])
print('a : ')
print(a)
print('b : ')
print(b)

a : 
[10 20 30 40 50]
b : 
[100 200 300 400 500]


### Create User Defined function for StandardScaler

In [7]:
def standardscaler(X):
    new_output = (X-X.mean())/X.std()
    return new_output


In [8]:
# Call in main Program
a = standardscaler(a)   # Call function
print(a)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [9]:
# Call in main Program
b = standardscaler(b)   # Call function
print(b)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
